# Generated by Django 2.2.6 on 2019-10-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='bloque',
            new_name='interior',
        ),
    ]
