# Generated by Django 2.2.6 on 2019-10-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0003_auto_20191022_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='celular_propietario',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion_propietario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='telefono_propietario',
            field=models.CharField(max_length=40),
        ),
    ]
