# Generated by Django 2.2.6 on 2019-10-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0004_auto_20191023_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='direccion_propietario',
            field=models.CharField(max_length=200),
        ),
    ]
