# Generated by Django 2.2.6 on 2019-10-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0005_auto_20191023_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='deposito',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
