# Generated by Django 2.2.6 on 2019-10-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0008_residente_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=9),
        ),
    ]
