# Generated by Django 2.2.6 on 2019-10-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0010_auto_20191023_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentes.Propiedad'),
        ),
    ]
