# Generated by Django 2.2.6 on 2019-10-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0011_auto_20191023_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentes.Propiedad')),
            ],
            options={
                'verbose_name': 'Parqueadero',
                'verbose_name_plural': 'Parqueaderos',
            },
        ),
    ]
