# Generated by Django 2.2.6 on 2019-10-21 21:53

from django.db import migrations, models
import django.db.models.deletion
import sardata.utils.uuid_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametricos', '__first__'),
        ('residentes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='')),
                ('numero_documento', models.CharField(max_length=12)),
                ('fecha_expedicion_documento', models.DateField()),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('celular_emergencia', models.CharField(max_length=12)),
                ('eps', models.CharField(max_length=50)),
                ('razon_social_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('arl', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametricos.Genero')),
                ('lugar_expedicion_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametricos.Municipio')),
                ('rh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametricos.RH')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametricos.TipoDocumento')),
                ('tipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametricos.TipoVisitante')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', sardata.utils.uuid_field.BinaryUUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.Propiedad')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitantes.Visitante')),
            ],
        ),
    ]
